name: Dominicana
favicon: null
layout_spectrum: 0.88432
typography_spectrum: 0.40679
title: Dominican Republic Vacation
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c0e5f8'
    - '#24292c'
    - '#949e86'
    - '#727b68'
    - '#fdfd9d'
  brandStrength: 0.9746529560070485
  lightness: 0.6728123943321407
  saturation: 0.45188645645976067
  rhythmicContrast: 0.2771679596044123
purpose: []
