name: Dominicana
favicon: null
layout_spectrum: 0.4110072839539498
typography_spectrum: 0.279977795900777
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9746529560070485
  lightness: 0.6728123943321407
  saturation: 0.45188645645976067
  rhythmicContrast: 0.2771679596044123
purpose: []
